# organization name, it's used to get github repo url, also in page title
name: SFantasy

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       Fantasy's BadgeBoard
description: project status at a glance
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
  - node-weather:
      repo: SFantasy/node-weather
  - is-valid:
      repo: SFantasy/node-validator
  - npm-generator:
      repo: SFantasy/generator
  - cdnsync:
      repo: SFantasy/cdnsync
  - ntrans:
      repo: SFantasy/node-translator
  - cntrain:
      repo: SFantasy/node-train
  - chepiao-sdk:
      repo: SFantasy/node-chepiao-sdk

# list of maintainers, this won't be sorted
maintainers:
 - name:    Fantasy Shao
   github:  SFantasy
   npm:     fantasyshao
   twitter: forFantasy
   gittip:  SFantasy
   email:   forever.fantasy27@gmail.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
