# organization name, it's used to get github repo url, also in page title
name: SFantasy

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       Fantasy's BadgeBoard
description: project status at a glance
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
    - node-weather
    - is-valid:
        repo: SFantasy/node-validator
    - npm-generator:
        repo: SFantasy/generator
    - cdnsync
    - ntrans:
        repo: teenworks/node-translator


# list of maintainers, this won't be sorted
maintainers:
 - name:    Fantasy Shao
   github:  SFantasy   # github account, required: we link to it
   npm:     fantasyshao   # npm account, required to determine lead maintainer
   twitter: forFantasy # twitter account, optional
   # gittip:  dougwilson   # gittub badge, optional
   email:   fantasyshao@icloud.com

 - name:    Fantasy Shao
   github:  SFantasy
   npm:     fantasyshao
   twitter: forFantasy
   email:   forever.fantasy27@gmail.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
